// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartHome.CoffeeMachine.Dal;

#nullable disable

namespace SmartHome.CoffeeMachine.Dal.Migrations
{
    [DbContext(typeof(CoffeeMachineDbContext))]
    [Migration("20230731152053_CoffeeMachineIsActive")]
    partial class CoffeeMachineIsActive
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmartHome.Common.Models.Coffee", b =>
                {
                    b.Property<Guid>("CoffeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CoffeeMachineId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CoffeeId");

                    b.HasIndex("CoffeeMachineId");

                    b.ToTable("Coffees");
                });

            modelBuilder.Entity("SmartHome.Common.Models.CoffeeMachine", b =>
                {
                    b.Property<Guid>("CoffeeMachineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CoffeeMachineSerialNr")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("CoffeeMachineId");

                    b.ToTable("CoffeeMachines");
                });

            modelBuilder.Entity("SmartHome.Common.Models.Coffee", b =>
                {
                    b.HasOne("SmartHome.Common.Models.CoffeeMachine", "CoffeeMachine")
                        .WithMany("Coffees")
                        .HasForeignKey("CoffeeMachineId");

                    b.Navigation("CoffeeMachine");
                });

            modelBuilder.Entity("SmartHome.Common.Models.CoffeeMachine", b =>
                {
                    b.Navigation("Coffees");
                });
#pragma warning restore 612, 618
        }
    }
}
